### ISSUE TITLE
Mighty Mo Plugin Inspiration

### ISSUE THREAD

**Issue by rtvenge** [hoverboard88/hb-server#1]
See what parts of Toby's plugin would be good for ours: https://github.com/themightymo/tmm-dashboard-customizations/blob/master/tmm-dashboard-customizations.php

**Comment by rtvenge** [comment]
@mbiersdo Thoughts on this? 
![CleanShot 2023-12-18 at 15 39 00@2x](https://github.com/hoverboard88/hb-server/assets/303836/7dd6fc61-fe36-4948-b93e-43977df440cd)

**Comment by mbiersdo** [comment]
👍

**Comment by rtvenge** [comment]
@mbiersdo are you good with our phone numbers on there? I'm starting to second guess it already. haha

**Comment by mbiersdo** [comment]
Keep phone numbers off
